### ISSUE TITLE
Error: "Failed to evaluate. Reason: Cannot evaluate because the thread is resumed"

### ISSUE THREAD

**Issue by shiuchunming** [Microsoft/java-debug#109]
Get error message "Failed to evaluate. Reason: Cannot evaluate because the thread is resumed" after getting input from vscode debug console using BufferedReader in Java.

    import java.io.BufferedReader;
    import java.io.IOException;
    import java.io.InputStreamReader;

    public class demo {
        public static void main(String args[]) throws IOException {
            int input;
            BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
            try {
               input = br.read();
            }
            catch(IOException e) {
                e.printStackTrace();
            }
            if(br != null) br.close();
            System.out.println("123"); // would not execute using debug console in vscode.
        }
    }

Here is the `launch.json`, which is basically a default one.

    {
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "java",
            "name": "compile",
            "mainClass": "demo",
            "request": "launch",
            "args": ""
        }

    ]
    }
---

![error](https://user-images.githubusercontent.com/28855544/32956894-2b41e99a-cbf5-11e7-9c71-fd3279da9077.png)

##### Environment
- Operating System: Elementary OS 0.4.1 Loki Built on "Ubuntu 16.04.3 LTS"
- JDK version: java 9.0.1
- Visual Studio Code version: 1.18.0
- Java extension version: 0.14.0

##### Steps To Reproduce
1. A console Java program getting user input with BufferedReader.
2. start debugging on debug console

##### Additional Informations

**Comment by andxu** [comment]
Hi shiuchunming, for the evaluation feature, it is required to be performed against a stopped(caused by pause) thread, if you continue the breakpoint, the evaluation functionality will be disabled, and your express will show " Cannot evaluate because the thread is resumed", if you are stopped at certain line of the code, it should be a bug when you cannot evaluate, so please tell me whether your code is stopped or not when the evaluation work cannot be continued.

**Comment by andxu** [comment]
It is by design that eval work can be only done at a the suspend JVM thread(caused by breakpoint/step)

**Comment by andxu** [comment]
https://github.com/Microsoft/java-debug/issues/161
