### ISSUE TITLE
cannot debug nashorn scripts

### ISSUE THREAD

**Issue by pmlopes** [Microsoft/java-debug#117]
IntelliJ and Netbeans (as an example) can debug javascript scripts running on the JVM as the Nashorn engine seems to generate the proper debug information at runtime when the scripts are compiled.

An example project can be seen in the netbeans project:

http://services.netbeans.org/synergy/server/api/attachment.php?id=197

I've tried to see if this plugin would also allow it, but sadly the breakpoint is not recognized and the code never stops. Also adding the special keyword `debugger;` will not be recognized and the IDE reports `Unverified Breakpoint`

**Comment by yaohaizh** [comment]
Duplicated with https://github.com/Microsoft/vscode-java-debug/issues/152
