### ISSUE TITLE
Error: "Failed to evaluate. Reason: Cannot evaluate because the thread is resumed"

### ISSUE THREAD

**Issue by gitorko** [Microsoft/java-debug#161]
`package com.demo.test.helloworld;
import java.util.Scanner;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class DemoApplication implements CommandLineRunner {

	public static void main(String[] args) {
		SpringApplication.run(DemoApplication.class, args);
	}

	@Override
	public void run(String... args) throws Exception {
		System.out.println("Please enter name");
		Scanner scanner = new Scanner(System.in);
		String name = scanner.nextLine();
		System.out.println("Hello: " + name);
		scanner.close();
	}
}`

`{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "java",
            "name": "Debug (Launch)-DemoApplication<helloworld>",
            "request": "launch",
            "cwd": "${workspaceFolder}",
            "console": "internalConsole",
            "stopOnEntry": false,
            "mainClass": "com.demo.test.helloworld.DemoApplication",
            "projectName": "helloworld",
            "args": ""
        },
        {
            "type": "java",
            "name": "Debug (Attach)",
            "request": "attach",
            "hostName": "localhost",
            "port": 0
        }
    ]
}`

vscode: 1.21.1

When run from maven custom goal: spring-boot:run it runs fine. When run via F5 debug it fails after input. "Failed to evaluate. Reason: Cannot evaluate because the thread is resumed." There are no breakpoints placed anywhere in the code. 

https://stackoverflow.com/questions/48642367/visual-studio-code-failed-to-evaluate-reason-cannot-evaluate-because-the-thre

**Comment by andxu** [comment]
Vscode has a confusing debug console, when user wants to input something to be read by System.in, the default settings generated by F5 in vscode doesn't work, see the following snapshot:

![image](https://user-images.githubusercontent.com/17075863/37746062-4b4e9fce-2db3-11e8-82b0-681ba6adc7d3.png)
The text marked by red circle doesn't mean the input but the evaluate, for example, if I input 1+100, it will give you 101 as the result
![image](https://user-images.githubusercontent.com/17075863/37746120-93a188e0-2db3-11e8-8c47-ffc37c662424.png)

To support user input, you have to change console from internalConsole(the default value)  to integratedTerminal, eg:
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "java",
            "name": "Debug (Launch)-App<simple-app>",
            "request": "launch",
            "cwd": "${workspaceFolder}",
            "console": "integratedTerminal",
            "stopOnEntry": false,
            "mainClass": "com.ms.samples.App",
            "projectName": "simple-app",
            "args": ""
        },
        {
            "type": "java",
            "name": "Debug (Attach)",
            "request": "attach",
            "hostName": "localhost",
            "port": 0
        }
    ]
}
```

![image](https://user-images.githubusercontent.com/17075863/37746220-209c60da-2db4-11e8-81e4-1bee8799bdae.png)

I want to emphasize again, even poplar ides like eclipse/intelj cannot evaluate when the program is running.

**Comment by andxu** [comment]
Dup as 109
