### ISSUE TITLE
.project .classpath files everywhere

### ISSUE THREAD

**Issue by Eskibear** [Microsoft/java-debug#183]
Once I open a java project, the VSCode extensions start to produce a HUGE number of  `.project` and `.classpath` files everywhere.  They really mess my project folder up. Can you just stop generating them or at least put them aside?

**Comment by Eskibear** [comment]
Forgot to say `.settings/` folder and `bin` folder

**Comment by Eskibear** [comment]
I've opened another issue here https://github.com/redhat-developer/vscode-java/issues/618

**Comment by yaohaizh** [comment]
Close this issue since it is already tracked by vscode java.
