### ISSUE TITLE
org.eclipse.jdt.core.prefs

### ISSUE THREAD

**Issue by gengu** [Microsoft/java-debug#185]
Could you tell me When did this setting occur?
How to set this default value from 1.5 to 1.8?

![image](https://user-images.githubusercontent.com/6317176/41901903-b4f99cc4-7964-11e8-824d-43f2372b249d.png)

**Comment by testforstephen** [comment]
What's your project type? 

For maven, it's parsed from the pom.xml.
```
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.7.0</version>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
            </plugin>
```

**Comment by gengu** [comment]
How could I change the version automatic , If I don't use this compiler  plugin？

**Comment by testforstephen** [comment]
The recommended way is using maven or gradle to compile your project. Currently we don't support other ways to change java target version. See the similar issue https://github.com/redhat-developer/vscode-java/issues/151 .
