### ISSUE TITLE
Publish java-debug as a p2 repo

### ISSUE THREAD

**Issue by fbricon** [Microsoft/java-debug#188]
... so it can easily be consumed by Eclipse based products.

Here's an example of a tycho based project to publish the java-debug plugin to a standalone p2 repo:
[java-debug-repo.zip](https://github.com/Microsoft/java-debug/files/2189968/java-debug-repo.zip)

If the p2 repo was built as part of the java-debug project. then the category.xml would declare 
`<bundle id="com.microsoft.java.debug.plugin" version="0.0.0.qualifier"/>` IIRC. In that case, all the repositories, dependencies declaration in pom.xml could be removed.

As for publishing the p2 repo, bintray.org is an alternative to self-hosting. See this [post](http://www.lorenzobettini.it/2016/02/publish-an-eclipse-p2-composite-repository-on-bintray/) describing bintray publishing.

cc @svor, @testforstephen

**Comment by testforstephen** [comment]
The p2 artifacts has been published to bintray server.

The latest p2 site: https://dl.bintray.com/vscjavaci/javadebug/
The history p2 site: https://dl.bintray.com/vscjavaci/javadebug/releases/0.11.0/

**Comment by testforstephen** [comment]
Since bintray is going to shutdown **May 2021**, do you guys still have projects using the java-debug p2 site? If not, i will stop publishing p2 site.

// cc: @fbricon @svor

**Comment by fbricon** [comment]
I don't use it, but I *think* it was needed by @svor for using Che at some point.

**Comment by svor** [comment]
> Since bintray is going to shutdown May 2021, do you guys still have projects using the java-debug p2 site? If not, i will stop publishing p2 site.
ok to me, we don't use it anymore

**Comment by testforstephen** [comment]
thank you all for the confirmation. i will stop p2 publishing.
