### ISSUE TITLE
Question on StepEvent in multi-thread app

### ISSUE THREAD

**Issue by asicfr** [Microsoft/java-debug#197]
It's not an issue but a question.  
  
I'm using your great project and **DebugSession** to debug my webapp powered by Tomcat.  
Thanks to **EventHub**, i get a lot of **StepEvent** on the "main" thread where Tomcat runs.  
But when I send an http request to my webapp / tomcat, i capture **MethodEntryEvent** for example but i do not capture any **StepEvent** on my code.  
Is there anything I missed ?  
Why i cannot capture **StepEvent** outside of the "main" thread ?   
Do I have to perform a particular action on existing threads?  
  
Whatever, thanks for all.

**Comment by testforstephen** [comment]
@asicfr How did you leverage the debugger? Are you just using `com.microsoft.java.debug.core`?

Back to your question, you need make your program stopping at a breakpoint, then step into/over/out the stack frame, in that case the **StepEvent** will be captured.

**Comment by asicfr** [comment]
@testforstephen I use that class : [Attach class](https://github.com/asicfr/cartographieApplication2/blob/master/applicationCarto/src/main/java/com/carto/applicarto/ConnectAndMonitorExternalAppJavaDebug.java)

**Comment by asicfr** [comment]
@testforstephen 
I surely missed something but when i use DebugSession on a single thread application, i can capture StepEvent without any breakpoint.
Why i cannot do that on a multi-thread application ?

My project is to use Jpda and StepEvent to trace the execute flow of an application.

Thanks

**Comment by testforstephen** [comment]
You can have a try with `threadStartRequest.setSuspendPolicy(EventRequest.EVENT_THREAD);`

**Comment by asicfr** [comment]
Ok, thanks you very much ... i will try.
Bye
