### ISSUE TITLE
Watchs Expression 

### ISSUE THREAD

**Issue by gengu** [Microsoft/java-debug#209]
![image](https://user-images.githubusercontent.com/6317176/44380641-13e38280-a53f-11e8-8311-efd8ce623d5c.png)

What caused this exception  "Cannot evalution expression because of java.lang.RuntimeException: Evaluations must contain either an expression or a block of well-formed statements." ？

**Comment by andxu** [comment]
We leverage the eclipse code for evaluation but unfortunately there are some bugs in eclipse we inherited:
![image](https://user-images.githubusercontent.com/17075863/44382237-c9660400-a546-11e8-8cd1-0223d9ee140d.png)

**Comment by andxu** [comment]
Please use 
```
new String[] {"a"};
```

**Comment by gengu** [comment]
six six six !
