### ISSUE TITLE
Failed to resolve classpath: Main class 'Main' isn't unique in the workspace

### ISSUE THREAD

**Issue by testforstephen** [Microsoft/java-debug#21]
Open a java folder, see the screenshot below.
<img width="369" alt="screen shot 2017-09-14 at 10 30 31 am" src="https://user-images.githubusercontent.com/14052197/30409470-cd01ab12-9937-11e7-8b1f-f9e2622dfa2e.png">

And click F5 to launch, it popup a message box saying that `Failed to resolve classpath: Main class 'Main' isn't unique in the workspace, please pass in specified projectname.`.

Apparently it's not a normal eclipse/maven/gradle project, but just a simple java file. In such case, these java files will be linked to a fake project. It seems the main class isn't unique in the fake project. But in such case, user doesn't know how to specify project name. We need figure out how to handle such kind of case.

**Comment by ansyral** [comment]
couldn't repro it yet because currently our debugger doesn't support single file debug without configuration. I'll test it after we [update our debugger with new debug protocol](https://github.com/Microsoft/vscode-java-debug/pull/87) and support single file debug following https://github.com/Microsoft/vscode/issues/33791#issuecomment-335248840

**Comment by ansyral** [comment]
could repro for projects that has main class whose package is default

**Comment by deed02392** [comment]
I had this error.

To repro: install the Java Extension Pack. Create a new maven generate archetype - select folder - choose maven-archetype-quickstart.

Provide groupid etc in the PowerShell console.

It generates the package and class `App`. 

Try to debug (Launch) the App class - not unique error.

I worked around this by renaming `App` file and class (obviously) to `Applol`.

**Comment by andxu** [comment]
The bug for 'Main' isn't unique in the workspace still happens, reopen it

**Comment by andxu** [comment]
I will collect this kind of error in telemetry later.

**Comment by andxu** [comment]
DUP as https://github.com/Microsoft/vscode-java-debug/issues/331
