### ISSUE TITLE
step into the constructor method and always go to ClassLoader.java

### ISSUE THREAD

**Issue by testforstephen** [Microsoft/java-debug#22]
Download the test project from https://github.com/vscjavaci/java-debug-ci/tree/master/testcase/8.nosource, and open it in vscode.

Set a breakpoint at line#3 of NoSourceTest.java, and click F5 to launch debug session.
Step into the constructor method, it always jumps to ClassLoader$loadClass in call stack.

Is there any way to filter the loadClass method?

**Comment by andxu** [comment]
Step filter feature will solve this issue on version 0.5.0
