### ISSUE TITLE
Failed to attach to remote debuggee VM.

### ISSUE THREAD

**Issue by negiDharmendra** [Microsoft/java-debug#252]
We have a vscode extension for [Gauge](https://gauge.org/)`(is a free and open source test automation framework.)`
While debugging the Java test, we programmatically make a connection with the process being debugged from our [Gauge vscode extention](https://marketplace.visualstudio.com/items?itemName=getgauge.gauge).

We are able to debug once in a given session. With consecutive debugging, we are getting the following error.

<img width="647" alt="screen shot 2019-01-03 at 2 13 45 pm" src="https://user-images.githubusercontent.com/15261737/50630367-973dc780-0f66-11e9-95ff-59c77e1b3e94.png">

Any help would be appreciated for this [issue](https://github.com/getgauge/gauge-vscode/issues/326).

**Comment by yaohaizh** [comment]
How to setup the java debug with the gauge extension? Any sample or document for this? @jdneo for test integration with java debugger.

**Comment by jdneo** [comment]
Hi @negiDharmendra,

If you want to programmatically attach to the Java Debugger, you need to set a timeout to wait for the JVM to get ready to be attached, for example, 500ms: https://github.com/Microsoft/vscode-java-test/blob/b671d2d8e32eeb99e19187358989d73ebc00284a/src/runners/baseRunner/BaseRunner.ts#L98-L107

> Note: The timeout may not cover all the cases but can highly decrease the possibility of this issue.

**Comment by negiDharmendra** [comment]
Hi @yaohaizh,

Please refer to [this document](https://docs.gauge.org/latest/installation.html#installation) for `Gauge` installation. In order to setup [Gauge java](https://github.com/getgauge/gauge-java) with [Gauge VsCode extension ](https://github.com/getgauge/gauge-vscode)we will have to build package from there respective branch `vscode_java_debug_support` as they are not released yet.

How about, if I build those packages and give them to you. Otherwise, I can explain how to build them locally.

**Comment by negiDharmendra** [comment]
@jdneo Thanks for the help. This issue has been resolved.
