### ISSUE TITLE
Cannot stop the debugging process automatically

### ISSUE THREAD

**Issue by bsaby** [microsoft/java-debug#273]
### Environment:
OS: Windows
JDK: 8
Java Test Runner Extension: 0.16.0

### Repro steps:
1. Open a test project in vscode
2. Debug test 

### Result:
Cannot actively stop the debugging process after running test
![image](https://user-images.githubusercontent.com/22470312/57913185-a3477780-78be-11e9-9bde-4000def7face.png)

**Comment by jdneo** [comment]
This can be reproduced in attach mode
