### ISSUE TITLE
[performance] should break out the while loop

### ISSUE THREAD

**Issue by tom-shan** [microsoft/java-debug#279]
https://github.com/microsoft/java-debug/blob/master/com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/AbstractDisconnectRequestHandler.java#L73-L94
Now it will costs about 5 seconds in the destroyLaunchFiles function, maybe there should have a break statement if no IOException catched in each loop for better performance.

**Comment by testforstephen** [comment]
nice finding.

**Comment by testforstephen** [comment]
@tom-shan Could you help make a pull request?
