### ISSUE TITLE
Server thread blocks until the client disconnects

### ISSUE THREAD

**Issue by marek1840** [microsoft/java-debug#286]
The `run` method in `AbstractProtocolServer` is blocking the thread on this line: [AbstractProtocolServer:92](https://github.com/microsoft/java-debug/blob/master/com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/protocol/AbstractProtocolServer.java#L92)

In my case, I may have to close the Debug Server in the middle of debugging while the whole application (within which the Debug Server operates) is still running, so I would like to do so as gracefully as I can.

Currently, it can be done by closing the I/O streams, as nothing else will unblock the thread on which the server is running. This approach results in an exception being throws in the server thread (i.e. socket closed) which is not something I would expect when closing the server.

Of course, the exception can be catched and ignored but it introduces an unnecessary level of complexity (to recognize it is an "expected exception" and not an actual issue).

**Comment by testforstephen** [comment]
How about sending a `disconnect` request to debug server when you want to proactively shut off the debugger ahead of time? It's more clean and consistent with the debug protocol design.

**Comment by marek1840** [comment]
Indeed it does work and is cleaner, thanks :)
