### ISSUE TITLE
Breakpoint / frame is off by 1

### ISSUE THREAD

**Issue by mfussenegger** [microsoft/java-debug#330]
I'm currently writing a [plugin for neovim](https://github.com/mfussenegger/nvim-dap) to add support for the debug adapter protocol and it seems to me that breakpoints are somehow interpreted wrong on the server side.

**java-debug version**: from master, commit `020721988021fcc3c01dd5d9006ff272ee010cec`

For example here:

<details>
  <summary>screenshot of breakpoint at println that is already executed</summary>

![screenshot](https://user-images.githubusercontent.com/38700/80280086-10d06a80-8702-11ea-81dc-cda7459dc3e7.png)

</details>

<details>
  <summary>set breakpoints request</summary>

```
{
  body = {
    breakpoints = { {
        id = 1,
        line = 18,
        message = "",
        verified = true
      } }
  },
  command = "setBreakpoints",
  request_seq = 4,
  seq = 5,
  success = true,
  type = "response"
}
```

</details>

<details>
  <summary>breakpoint event</summary>

```
{
  body = {
    breakpoint = {
      id = 1,
      line = 18,
      message = "",
      verified = true
    },
    reason = "new",
    type = "breakpoint"
  },
  event = "breakpoint",
  seq = 11,
  type = "event"
}
```

</details>

You can see a breakpoint in line 18, but in the output window `1` is already showing up. I'd except that to happen only after stepping past it.

<details>
  <summary>stopped event and frame response</summary>

```
{
  body = {
    allThreadsStopped = false,
    reason = "breakpoint",
    threadId = 1,
    type = "stopped"
  },
  event = "stopped",
  seq = 12,
  type = "event"
}
```

```
{
  body = {
    stackFrames = { {
        column = 1,
        id = 1,
        line = 18,
        name = "ListsTest.testMapperFunctionIsAppliedToEachItem()",
        source = {
          name = "ListsTest.java",
          path = "/path/to/src/test/java/ListsTest.java",
          sourceReference = 0
        }
      }, {
```

</details>

If I step (`next`), then `numbers` is already in scope:

<details>
<summary>numbers in scope too early</summary>

![screenshot](https://user-images.githubusercontent.com/38700/80280187-dd421000-8702-11ea-98bc-9b10684494b6.png)

</details>

If I'm using [debugpy](https://github.com/microsoft/debugpy) it works as I'd expect, which is why I don't think it is a bug in my plugin. The breakpoint is set at line 5, where it stopped, and the scopes are tmpty:

<details>
<summary> similar scenario with debugpy, working as expected</summary>

![screenshot](https://user-images.githubusercontent.com/38700/80280377-031be480-8704-11ea-8970-b440414378be.png)

After stepping, `x` is in scope:

![screenshot](https://user-images.githubusercontent.com/38700/80280391-0fa03d00-8704-11ea-871a-1094243be47c.png)

</details>

<details>
<summary>initialization request from nvim-dap</summary>

```
{
  arguments = {
    adapterID = "nvim-dap",
    clientId = "neovim",
    clientname = "neovim",
    columnsStartAt1 = true,
    locale = "en_US.UTF-8",
    pathFormat = "path",
    supportsRunInTerminalRequest = true
  },
  command = "initialize",
  seq = 0,
  type = "request"
}
```

</details>

**Comment by testforstephen** [comment]
> **initialization request from nvim-dap**
{
  arguments = {
    adapterID = "nvim-dap",
    clientId = "neovim",
    clientname = "neovim",
    columnsStartAt1 = true,
    locale = "en_US.UTF-8",
    pathFormat = "path",
    supportsRunInTerminalRequest = true
  },
  command = "initialize",
  seq = 0,
  type = "request"
}

Apparently you didn't set linesStartAt1 to true. By default, the line will start with 0.

**Comment by mfussenegger** [comment]
> Apparently you didn't set linesStartAt1 to true. By default, the line will start with 0.

That's true and I can confirm that setting it explicitly solves the issue, but according [to the spec](https://microsoft.github.io/debug-adapter-protocol/specification#Requests_Initialize), the default should be true anyhow:

```
 /**
   * If true all line numbers are 1-based (default).
   */
  linesStartAt1?: boolean;
```

So seems like java-debug is setting the wrong default?
