### ISSUE TITLE
many tests failing

### ISSUE THREAD

**Issue by cyrfer** [microsoft/java-debug#388]
I would like to contribute a feature enhancement to a [related project](https://github.com/cyrfer/vscode-java-debug) that depends on this project.

I just cloned this repo and ran the tests in VS Code Testing interface.

> 4/47 tests passed (8.51%)

![image](https://user-images.githubusercontent.com/4392990/136486496-e2a80c6c-1f53-48a0-b2cb-4b3f92a0ade9.png)

**Comment by testforstephen** [comment]
Currently there is issue when running this project in VS Code with JDK 1.8. 

A temporary workaround is to make "JavaSE-1.8" to point to JDK 11 in "java.configuration.runtimes" setting.
```
    "java.configuration.runtimes": [
        // {
        //     "name": "JavaSE-1.8",
        //     "path": "/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home"
        // },
        {
            "name": "JavaSE-1.8",
            "path": "/Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home"
        }
   ]
```


Or use the command line "**./mvnw clean verify**" to run test.

**Comment by cyrfer** [comment]
@testforstephen please provide more info. When I attempt to edit `.vscode/setttings.json` with the key above, I see the following message:
> This setting can only be applied in user settings in local window or in remote settings in remote window.

When I try to use `./mvnw clean verify` I see the following:

```bash
Tests run: 47, Failures: 0, Errors: 43, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Java Debug Server for Visual Studio Code :: Parent . SUCCESS [  0.125 s]
[INFO] Java Debug Server for Visual Studio Code :: Debugger Core FAILURE [ 13.527 s]
[INFO] Java Debug Server for Visual Studio Code :: Debugger Plugin SKIPPED
[INFO] Java Debug Server for Visual Studio Code :: P2 Update site SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 23.575 s
[INFO] Finished at: 2021-10-08T09:41:55-07:00
[INFO] Final Memory: 64M/230M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project com.microsoft.java.debug.core: There are test failures.
```

I have both 1.8 and 11 installed on my system. 11 is the default JDK.
```bash
java --version
openjdk 11.0.8 2020-07-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.8+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.8+10, mixed mode)
```

The problem also occurs when using `mvn` in the terminal.

This fails:
```bash
mvn clean package
```

This succeeds:
```bash
mvn clean package -Dmaven.test.skip=true
```

**Comment by testforstephen** [comment]
i didn't get errors when running `./mvnw clean verify` in terminal.

Please notice that mvn command line uses JAVA_HOME environment variable to find a JDK. You need to use `./mvnw -v` to check the maven runtime.
