### ISSUE TITLE
Setting to disable lazy loading from toString()

### ISSUE THREAD

**Issue by eakst7** [microsoft/java-debug#407]
PR #401 introduced lazy loading values from toString() methods.

Unfortunately, this can mean a lot of additional clicking necessary to show the desired debug information.  Setting `java.debug.settings.showToString` to false disables the entire feature.  It would be beneficial to disable only the lazy loading.

![image](https://user-images.githubusercontent.com/16217243/162052875-65212e1a-2844-4891-904f-d964f0ad1b12.png)

**Comment by testforstephen** [comment]
VS Code 1.67.0 has provided such a setting `debug.autoExpandLazyVariables` to allow you to expand the variable full value by default. So closing this issue.
