### ISSUE TITLE
如何debug调试外包jar包代码

### ISSUE THREAD

**Issue by swtseaman** [microsoft/java-debug#408]
项目通过maven引用其他的jar包进行开发；在debug的时候需要跟到其他jar里面看情况；
但是跟过去是 class文件，上面写有
 // Failed to get sources. Instead, stub sources have been generated by the disassembler.
 // Implementation of methods is unavailable.

尝试在代码右键  选择 附加源代码，  通过.m2/repository/下找到对应jar文件后，依然没有任何变化

请问应该如何使用

**Comment by swtseaman** [comment]
版本: 1.66.2
提交: dfd34e8260c270da74b5c2d86d61aee4b6d56977
日期: 2022-04-11T07:47:29.396Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Darwin arm64 21.3.0

**Comment by testforstephen** [comment]
Duplicate with https://github.com/microsoft/vscode-java-debug/issues/1155
