### ISSUE TITLE
lambda expression doesn't apply to the right java file.

### ISSUE THREAD

**Issue by andxu** [Microsoft/java-debug#41]
Step: use debugger to debug itself, step in computeIfAbsent in StackTraceRequestHandler.java@112

![image](https://user-images.githubusercontent.com/17075863/30673467-e8f0682c-9ea5-11e7-9326-287ae42fb4fc.png)

**Comment by testforstephen** [comment]
The lambda expression issue has been resolved. As to the improvement of method names in call stack view is duplicated with https://github.com/Microsoft/java-debug/issues/43
