### ISSUE TITLE
Include class name in stack frame

### ISSUE THREAD

**Issue by andxu** [Microsoft/java-debug#43]
Currently only the method is displayed:

![image](https://user-images.githubusercontent.com/17075863/30675009-8cdcd880-9eb0-11e7-9a41-7c004f6a209e.png)

see eclipse:
![image](https://user-images.githubusercontent.com/17075863/30675017-990c78b8-9eb0-11e7-9f96-b14c329a9a70.png)

**Comment by testforstephen** [comment]
The code has merged to master branch.
