### ISSUE TITLE
Unknown event "processid"

### ISSUE THREAD

**Issue by supercow112** [microsoft/java-debug#460]
Hello!

I noticed that `LaunchRequestHandler` will [send a message](https://github.com/microsoft/java-debug/blob/791cd97260f204e2cb851e79287881f6d634c1b4/com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/LaunchRequestHandler.java#L196) to the client with "event": "processid".

This does not correspond to anything in the DAP specifications. In fact, the only message that contains information with `processId` and `shellProcessId` is a `RunInTerminalResponse` ([link](https://microsoft.github.io/debug-adapter-protocol/specification#Reverse_Requests_RunInTerminal)). Still, this describes a response rather than an event. Furthermore, `LaunchRequestHandler` will send this "processid" event even when `supportsRunInTerminalRequest` is set to false. 

Even if this event is not supported by DAP specs, should a client be expected to process this?

**Comment by testforstephen** [comment]
this is a custom event. By default, the client can just ignore it.

**Comment by supercow112** [comment]
Thank you!
