### ISSUE TITLE
launcherScript usage

### ISSUE THREAD

**Issue by supercow112** [microsoft/java-debug#462]
I have a bash script that runs a java program for me. I was wondering if I can get the plugin to run this script through the `launcherScript` argument without runInTerminal support. 

To this end, I have the following question: 
In "debug" mode, it seems that the `launcherScript` is only used [if runInTerminal is supported](https://github.com/microsoft/java-debug/blob/42f9ac7d4843b75b1fdde64762d8c5ce4a4c51b2/com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/LaunchWithDebuggingDelegate.java#L81). Why is that the case? Can we not invoke the script using `Runtime.getRuntime().exec(**launcherScript + args**)`?

**Comment by testforstephen** [comment]
The launcherScript is used to enforce a UTF-8 encoding for terminal before. Now this script is deprecated, we don't use it in VS Code. For your case, you should use "[preLaunchTask](https://code.visualstudio.com/docs/editor/debugging#:~:text=Debug%20quick%20pick.-,preLaunchTask,-%2D%20to%20launch%20a)" to specify your task script.

**Comment by supercow112** [comment]
Thanks for the response! I just want to clarify.
Is "preLaunchTask" specifying a task to VS Code or to the debug server? I'm not using VS Code so I want to instruct the debug server to run the script for me. A quick search for "preLaunchTask" in this repo comes up empty so I'm wondering if this is supported. If not, is there a way to instruct the server to launch the debuggee through my script?
