### ISSUE TITLE
Dependence on Eclipse JDT Language Server?

### ISSUE THREAD

**Issue by supercow112** [microsoft/java-debug#469]
I was wondering if it was possible to decouple the DAP server from the Eclipse JDT Language Server. At least the functionality that is under `com.microsoft.java.debug.core`. From file searching, `debug.core` has no dependence on any jdt classes.

Is this possible and if so, is there an existing option/implementation for this?

Many thanks.

**Comment by testforstephen** [comment]
`com.microsoft.java.debug.core` has no dependency on language server. What's your use case for requesting this?

**Comment by supercow112** [comment]
I want to understand if the JDT LS is necessary for simple debugging. By simple debugging, I'm referring to  debugging with a set of functionalities that is a subset of those in `com.microsoft.java.debug.core`, e.g. breakpoints, stepping through, local variables, and expression evaluation. 

More specifically, I'm curious if it is feasible to take the methods defined in `com.microsoft.java.debug.core` and create a lightweight DAP server that does not depend on the Language Server. It feels like a lot when I'm using very little!

It seems like the JSON server that handles the DAP requests and the methods for said requests are already in `com.microsoft.java.debug.core`. Therefore, this seems possible but I would greatly appreciate your input.

Many thanks!

**Comment by testforstephen** [comment]
> More specifically, I'm curious if it is feasible to take the methods defined in com.microsoft.java.debug.core and create a lightweight DAP server that does not depend on the Language Server. It feels like a lot when I'm using very little!
> 
> It seems like the JSON server that handles the DAP requests and the methods for said requests are already in com.microsoft.java.debug.core. Therefore, this seems possible but I would greatly appreciate your input.

Yes, you can, but you still have to implement a bunch of providers by your own. We decouple some IDE specific capabilities such as source mapping, breakpoint resolving, expression compilation into a separate plugin `com.microsoft.java.debug.plugin`. You can provide a simple implementation for these provider interfaces such as [ISourceLookUpProvider](https://github.com/microsoft/java-debug/blob/main/com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/ISourceLookUpProvider.java), [IEvaluationProvider.java](https://github.com/microsoft/java-debug/blob/main/com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/IEvaluationProvider.java) etc.
