### ISSUE TITLE
Tar release 0.44.0 fails to build

### ISSUE THREAD

**Issue by mmackay055** [microsoft/java-debug#479]
When building from release **0.44.0** the build fails with the following error:
[ERROR] Cannot resolve project dependencies:
[ERROR]   Software being installed: com.microsoft.java.debug.plugin 0.44.0
[ERROR]   Missing requirement: org.eclipse.jdt.ls.core 1.22.0.202304061040 requires 'osgi.bundle; org.eclipse.lsp4j [0.20.0.0,0.21.0)' but it could not be found
[ERROR]   Cannot satisfy dependency: com.microsoft.java.debug.plugin 0.44.0 depends on: osgi.bundle; org.eclipse.jdt.ls.core 0.0.0

This occurred with several previous versions as well. When I clone the repo it builds fine.

**Comment by testforstephen** [comment]
Duplicated with https://github.com/microsoft/java-debug/issues/472. It has been fixed in latest code.
