### ISSUE TITLE
Separate debugger protocol binding classes from the java debugger implementation

### ISSUE THREAD

**Issue by fbricon** [Microsoft/java-debug#50]
Java bindings for VSCode debugger protocol should be made available standalone, so that other debuggers of the VS Code protocol can be implemented in Java.

See https://twitter.com/mickaelistria/status/913026200364371968

**Comment by testforstephen** [comment]
The java bindings are placed at the package `com.microsoft.java.debug.core.protocol` of com.microsoft.java.debug.core.jar.

Now the debug core is on nexus central repository, you can easily to add it as dependency. See the comment from issue   https://github.com/Microsoft/java-debug/issues/77.
