### ISSUE TITLE
Documentation | How can I launch the DAP server from the command line?

### ISSUE THREAD

**Issue by miamagana** [microsoft/java-debug#508]
Hello, I am working on implementing my own DAP client and I'd like to know how to launch the DAP server from the CLI so I can start a debug session. 

I am currently starting the Eclipse LSP by using the following command: 

```
java -Declipse.application=org.eclipse.jdt.ls.core.id1 \
  	-Dosgi.bundles.defaultStartLevel=4 \
  	-Declipse.product=org.eclipse.jdt.ls.core.product \
  	-Dlog.level=ALL \
  	-noverify \
  	-Xmx1G \
  	--add-modules=ALL-SYSTEM \
  	--add-opens java.base/java.util=ALL-UNNAMED \
  	--add-opens java.base/java.lang=ALL-UNNAMED \
  	-jar ./plugins/org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar  \
  	-configuration ./config_linux \
  	-DCLIENT_PORT=5555 \
  	-data <data-folder>
```
I wanted to use this package as a DAP server without having to rely on the vs-code extension is this possible?

**Comment by testforstephen** [comment]
See https://github.com/microsoft/java-debug/tree/0.49.0#usage-with-eclipsejdtls
