### ISSUE TITLE
Are there any plans for 0.50 release?

### ISSUE THREAD

**Issue by VladimirMakaev** [microsoft/java-debug#523]
There hasn't been any release pushed since end of August, are there any plans to make one any time soon?

**Comment by testforstephen** [comment]
0.50 is already released on Nov. 1st, just forgot tagging it in GitHub.

**Comment by VladimirMakaev** [comment]
Thanks @testforstephen! I'm mostly interested in release in maven repository. E.g. https://mvnrepository.com/artifact/com.microsoft.java/com.microsoft.java.debug.core. Is this managed externally or by ci in this repo?

**Comment by testforstephen** [comment]
0.50.0 is available in maven central.
