### ISSUE TITLE
Build failure: TypeFilter cannot be resolved to a type

### ISSUE THREAD

**Issue by bsolar17** [microsoft/java-debug#534]
I'm trying to build on MacOS and I'm having the following compilation failure:

```
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:4.0.3:compile (default-compile) on project com.microsoft.java.debug.plugin: Compilation failure: Compilation failure:
[ERROR] /Users/bsolar/Projects/java-debug/com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/plugin/internal/CompletionProposalRequestor.java:[324]
[ERROR]         return declaringType != null && org.eclipse.jdt.ls.core.internal.contentassist.TypeFilter.isFiltered(declaringType);
[ERROR]                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[ERROR] org.eclipse.jdt.ls.core.internal.contentassist.TypeFilter cannot be resolved to a type
[ERROR] 1 problem (1 error)
```

**Comment by Redy1908** [comment]
Same problem

**Comment by Libadoxon** [comment]
Same on Linux, from want I can tell this is caused by a dependency change. Though then one has to ask themselves why the dependencies are not pinned to ensure reproducibility. This shouldn't be too much of a hassle but I'm not a Java dev so I might be wrong there. As a workaround you can comment of the right side of the if condition, so that the code looks like that:
```java
return declaringType != null /*&& org.eclipse.jdt.ls.core.internal.contentassist.TypeFilter.isFiltered(declaringType)*/;
```
This at least allows the package to build but probable unfixes the issues mentioned in the code ([Jdtls 1212](https://github.com/eclipse-jdtls/eclipse.jdt.ls/issues/1212))

**Comment by bsolar17** [comment]
> Though then one has to ask themselves why the dependencies are not pinned to ensure reproducibility. This shouldn't be too much of a hassle but I'm not a Java dev so I might be wrong there.

I think this is due to [this file](https://github.com/microsoft/java-debug/blob/main/com.microsoft.java.debug.target/com.microsoft.java.debug.tp.target). E.g:

```
<unit id="org.eclipse.jdt.source.feature.group" version="0.0.0"/>
```

My understanding is that `version="0.0.0"` means "use the latest version", which of course is not reproducible.

**Comment by Libadoxon** [comment]
> My understanding is that `version="0.0.0"` means "use the latest version", which of course is not reproducible.

You're probable right, hope that this changes. While I can of course understand that that would create extra work, I still think its very important for a version to always build. A compromise maybe would be to only pin the dependencies for every release to ensure at least reproducibility there.
