### ISSUE TITLE
Remote eclipse binary repository removed

### ISSUE THREAD

**Issue by Libadoxon** [microsoft/java-debug#537]
It seems that Eclipse removed the repository at https://download.eclipse.org/eclipse/updates/4.31-I-builds/, which is needed in `com.microsoft.java.debug.target/com.microsoft.java.debug.tp.target`. My knowledge about Eclipse is limited but from my research is seems that this is a repository that normally gets used for unstable dev binaries. 

As a workaround or maybe a fix I changed the url to https://download.eclipse.org/eclipse/updates/4.31 which compiled but I didn't do any test to check if everything works correctly

**Comment by testforstephen** [comment]
@Libadoxon thanks for reporting the issue, yes, we need to update the target platform to 4.31 release url.
