### ISSUE TITLE
Debugging support for other languages (JSR045) (SMAP)

### ISSUE THREAD

**Issue by b-tsao** [microsoft/java-debug#572]
I'm trying to use java-debug to debug a file that was translated to java with a smap. After adding the smap in the SourceDebugExtension attribute and starting up the debug in VSCode via vscode-java-debug I can see the threads paused and the variables but the first thing that jumps out is there's no highlight and the thread isn't focused
<img width="1791" alt="image" src="https://github.com/user-attachments/assets/e5003dfa-a4d3-4fcd-94e6-1cb7277838c9">
After clicking on the thread I can see the variables are correct but still no highlight.
<img width="1786" alt="image" src="https://github.com/user-attachments/assets/87baba50-5492-4529-a3c5-8011672dc9d5">

Any idea how I can get this to work?

**Comment by testforstephen** [comment]
You can see the top stack frame is grey, that means its source code is unavailable, and vscode does not know how to render it.

**Comment by b-tsao** [comment]
Hi @testforstephen,

Thank you for your response.

I've tried to provide the source code path to vscode via mainClass and sourcePaths, unfortunately neither have worked.

```
vscode.debug.startDebugging(undefined, {
  type: 'java',
  name: 'Java Stored Procedure Debugger',
  request: 'attach',
  hostName: jvmIp,
  port: jvmPort,
  mainClass: SPDebugSession.javaPath,
  sourcePaths: [SPDebugSession.javaPath]
}).then(...)
```

One thing I also tried was I used a java program that did work for debug and renamed the ext to `.sqlj`, with the alias in package.json for vscode extension as follows:
```
      {
        "id": "java",
        "aliases": [
          "Java",
          "java",
          "sqlj"
        ],
        "extensions": [
          ".java",
          ".sqlj"
        ]
      }
```
and it hit the same problem.

Is java-debug hard coded to seek out `.java` files or perhaps you could point me in the right direction?

**Comment by testforstephen** [comment]
Here is the code to resolve the source for the stack frame, please take a look by yourself. https://github.com/microsoft/java-debug/blob/main/com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/StackTraceRequestHandler.java

**Comment by b-tsao** [comment]
Thank you @testforstephen, I was able to get it working by removing the file path in the smap.
