### ISSUE TITLE
Publish com.microsoft.java.debug.core to a maven repository

### ISSUE THREAD

**Issue by smarter** [Microsoft/java-debug#77]
I'm currently working on a debug server implementation for Scala based on java-debug, it'd be really helpful if you could publish the `com.microsoft.java.debug.core` package to a repository online such as http://central.sonatype.org/, that way I could depend on it in my own project easily.

**Comment by akaroml** [comment]
@testforstephen please take a look and publish to Maven central repository. We'll need to sign the jars before publishing.

**Comment by testforstephen** [comment]
The java-debug jars has been published to sonatype nexus repository manager successfully (https://oss.sonatype.org/content/groups/public/com/microsoft/java/). Now you just need add the following dependency in your pom.xml to use java debug core.
```
  <dependencies\>
    <dependency>
      <groupId>com.microsoft.java</groupId>
      <artifactId>com.microsoft.java.debug.core</artifactId>
      <version>0.5.0</version>
    </dependency>
  </dependencies>
```

@smarter @fbricon @rotemso fyi
